classdef Mouse < fieldlab.sources.Subject
    
    methods
        
        function obj = Mouse()
            import symphonyui.core.*;
            import edu.washington.*;
            
            obj.addProperty('genotype', {}, ...
                'type', PropertyType('cellstr', 'row', {'C57B6', 'Thy1-GFP', 'rd10',...
                                'Cx36-rod KO', 'Cx36-cone KO', 'CRB1null;ires-GFP9', 'CRB1null-wt',...
                                'CRB1-null' 'Cx36-/-',...
                                'Ai14', 'Opa1-flox', 'hoxd10', 'Cng-neo/neo'}), ... 
                'description', 'Genetic strain');
            
            photoreceptors = containers.Map();
            photoreceptors('mCone') = struct( ...
                'collectingArea', containers.Map({'photoreceptorSide', 'ganglionCellSide'}, {0.20, 1.00}), ...
                'spectrum', importdata(riekelab.Package.getCalibrationResource('sources', 'mouse', 'm_cone_spectrum.txt')));
            photoreceptors('rod') = struct( ...
                'collectingArea', containers.Map({'photoreceptorSide', 'ganglionCellSide'}, {0.50, 0.87}), ...
                'spectrum', importdata(riekelab.Package.getCalibrationResource('sources', 'mouse', 'rod_spectrum.txt')));
            photoreceptors('sCone') = struct( ...
                'collectingArea', containers.Map({'photoreceptorSide', 'ganglionCellSide'}, {0.20, 1.00}), ...
                'spectrum', importdata(riekelab.Package.getCalibrationResource('sources', 'mouse', 's_cone_spectrum.txt')));
            obj.addResource('photoreceptors', photoreceptors);
            
            obj.addAllowableParentType([]);
        end
        
    end
    
end

