classdef PatchA < symphonyui.core.descriptions.RigDescription

  methods

    function createRig(obj)
      import symphonyui.builtin.daqs.*;
      import symphonyui.builtin.devices.*;
      import symphonyui.core.*;
      %import admin.devices.*;
      import common.*;

      %% DAQ controller
      daq = symphonyui.builtin.daqs.HekaDaqController();
      obj.daqController = daq;

      digitalStream1 = daq.getStream('doport1');

      %% Amplifier 1
      % Command voltage: ao0, Primary input: ai0
      amp1 = symphonyui.builtin.devices.MultiClampDevice('Amp1', 1, []);
      amp1.bindStream(daq.getStream('ao0'));
      amp1.bindStream(daq.getStream('ai0'));
      obj.addDevice(amp1);

      %% Amplifier 2
      % Command voltage: ao1, Primary input: ai1
      amp2 = symphonyui.builtin.devices.MultiClampDevice('Amp2', 2, []);
      amp2.bindStream(daq.getStream('ao1'));
      amp2.bindStream(daq.getStream('ai1'));
      obj.addDevice(amp2);

      %% White LED (+ its color and ND filter wheels) -- currently disabled
      % Output: ao2, Input: ai2
      % whiteLED = symphonyui.builtin.devices.LedDevice(  ...
      %   'LED White',                              ...
      %   daq,                                      ...
      %   'White',                                  ...
      %   'outputStream', 'ao2',                    ...
      %   'inputStream', 'ai2',                     ...
      %   'outputTargetUnits', 'V',                 ...
      %   'inputTargetUnits', 'V',                  ...
      %   'maximum', 10,                            ...
      %   'calibrationLUT', '(None)',               ...
      %   'spectrum', '(None)',                     ...
      %   'ndLUT', '(None)',                        ...
      %   'nd', '',                                 ...
      %   'isLambdaFixed', true,                    ...
      %   'Manufacturer', 'Cairn'                   ...
      %   );
      %
      % Color filter wheel: digital ch 1, COM12
      % whiteLED_cfw = ThorlabsFilterWheel(         ...
      %   'White Color Filter',                     ...
      %   'COM12',                                  ...
      %   'WheelLabels', {'White Color Filters'},   ...
      %   'PositionLabels',                         ...
      %   {                                         ...
      %   {450, 470, 500, 560, 600, 620},           ...
      %   },                                        ...
      %   'verbose', true,                          ...
      %   'Timeout', 0.25                           ...
      %   );
      % whiteLED_cfw.bindPairedDevice(1, whiteLED, 'Color');
      % whiteLED_cfw.bindStream( digitalStream1 );
      % digitalStream1.setBitPosition( whiteLED_cfw, 1 );
      %
      % ND filter wheel: digital ch 2, COM10
      % whiteLED_nd_fw = ThorlabsFilterWheel(       ...
      %   'White ND Filter',                        ...
      %   'COM10',                                  ...
      %   'WheelLabels', {'White ND Filters'},      ...
      %   'PositionLabels',                         ...
      %   {                                         ...
      %   {0.0, 0.5, 1.0, 2.0, 3.0, 4.0},           ...
      %   },                                        ...
      %   'verbose', true,                          ...
      %   'Timeout', 0.25                           ...
      %   );
      % whiteLED_nd_fw.bindPairedDevice(1, whiteLED, 'ND');
      % whiteLED_nd_fw.bindStream( digitalStream1 );
      % digitalStream1.setBitPosition( whiteLED_nd_fw, 2 );
      %
      % obj.addDevice(whiteLED);
      % obj.addDevice(whiteLED_cfw);
      % obj.addDevice(whiteLED_nd_fw);

      %% 405 nm LED (+ its ND filter wheel) -- currently disabled
      % Output: ao3, Input: ai3
      % LED405 = symphonyui.builtin.devices.LedDevice(    ...
      %   'LED 405 nm',                             ...
      %   daq,                                      ...
      %   405,                                      ...
      %   'outputStream', 'ao3',                    ...
      %   'inputStream', 'ai3',                     ...
      %   'outputTargetUnits', 'V',                 ...
      %   'inputTargetUnits', 'V',                  ...
      %   'maximum', 9,                             ...
      %   'calibrationLUT', '(None)',               ...
      %   'spectrum', '(None)',                     ...
      %   'ndLUT', '(None)',                        ...
      %   'nd', '',                                 ...
      %   'isLambdaFixed', true,                    ...
      %   'Manufacturer', 'Cairn'                   ...
      %   );
      %
      % ND filter wheel: digital ch 3, COM11
      % LED405_nd_fw = ThorlabsFilterWheel(         ...
      %   '405 ND Filter',                          ...
      %   'COM11',                                  ...
      %   'WheelLabels', {'LED 405 ND Filter'},     ...
      %   'PositionLabels',                         ...
      %   {                                         ...
      %   {0.0, 0.5, 1.0, 2.0, 3.0, 4.0},           ...
      %   },                                        ...
      %   'verbose', true,                          ...
      %   'Timeout', 0.25                           ...
      %   );
      % LED405_nd_fw.bindPairedDevice(1, LED405, 'ND');
      % LED405_nd_fw.bindStream( digitalStream1 );
      % digitalStream1.setBitPosition( LED405_nd_fw, 3 );
      %
      % obj.addDevice(LED405);
      % obj.addDevice(LED405_nd_fw);

      %% Motorized filter wheel (ThorLabs, common.devices.FilterWheelDevice) -- currently disabled
      % filterWheel = common.devices.FilterWheelDevice( ...
      %   'comPort', 'COM12',                           ...
      %   'ndfValues', [1.0, 2.0, 3.0, 4.0, 5.0, 0]      ...
      %   );
      % Bound to an otherwise-unused stream so its config is written to
      % each epoch.
      % filterWheel.bindStream(digitalStream1);
      % daq.getStream(digitalStream1).setBitPosition(filterWheel, 1);
      % obj.addDevice(filterWheel);

      %% Oscilloscope
      % Digital bit position: 1 (Tektronix)
      % scope = GenericDevice(  ...
      %   'Oscilloscope',                           ...
      %   symphonyui.core.Measurement.UNITLESS,     ...
      %   daq,                                      ...
      %   'digitalStream', 'doport1',               ...
      %   'type', 'Oscilloscope',                   ...
      %   'bitPosition', 1,                         ...
      %   'manufacturer', 'Tektronix'               ...
      %   );
      % obj.addDevice(scope);
      % 
      % %% Temperature probe
      % % Input: ai4 (Warner Instruments TC-324C)
      % tempProbe = GenericDevice(  ...
      %   'TC-324C',                                ...
      %   'dV',                                     ...
      %   daq,                                      ...
      %   'inputStream', 'ai4',                     ...
      %   'type', 'Temperature Probe',              ...
      %   'manufacturer', 'Warner Instruments'      ...
      %   );
      % tempProbe.setResource('conversion_units', '°C');
      % obj.addDevice(tempProbe);

    end
  end
end