classdef PatchASim < symphonyui.core.descriptions.RigDescription
    % Simulated version of the PatchA rig for testing.
    %
    % Identical to PatchA except it uses the simulated HEKA DAQ controller
    % (HekaSimulationDaqController), so it requires no attached ITC hardware.
    % The MultiClamp devices still talk to MultiClamp Commander, which can be
    % run in demo mode.

    methods

        function obj = PatchASim()
            import symphonyui.builtin.daqs.*;
            import symphonyui.builtin.devices.*;
            import symphonyui.core.*;
            import common.*;

            %% DAQ controller (simulated HEKA ITC -- no hardware required)
            daq = HekaSimulationDaqController();
            obj.daqController = daq;

            % Digital stream the filter wheels (and the disabled LED / scope
            % devices) are bound to, so their configuration settings are
            % written to each epoch.
            digitalStream1 = daq.getStream('doport1');

            %% Amplifier 1  (command: ao0, primary input: ai0)
            amp1 = MultiClampDevice('Amp1', 1).bindStream(daq.getStream('ao0')).bindStream(daq.getStream('ai0'));
            obj.addDevice(amp1);

            %% Amplifier 2  (command: ao1, primary input: ai1)
            amp2 = MultiClampDevice('Amp2', 2).bindStream(daq.getStream('ao1')).bindStream(daq.getStream('ai1'));
            obj.addDevice(amp2);

            %% Filter wheels (ThorLabs motorized ND wheels)
            % NOTE: PLACEHOLDER WIRING. Confirm/replace the comPort, ndfValues,
            % and digital bit positions below for each wheel before use on the
            % real rig. COM ports carried over from the old commented config
            % (COM12, COM10, COM11); ndfValues left at the device default.
            % Each wheel is driven over its serial (COM) port; the bindStream
            % to digitalStream1 only logs its configuration to each epoch, so
            % every wheel needs a UNIQUE bit position. On this sim rig a wheel
            % whose COM port is absent simply stays disconnected (isOpen=false)
            % without blocking rig initialization.
            filterWheel1 = fieldlab.devices.FilterWheelDevice( ...
                'name', 'Filter Wheel 1', ...
                'comPort', 'COM12', ...              % TODO: confirm COM port
                'ndfValues', [0 0.5 1.0 2.0 3.0 4.0]);% TODO: confirm ND values
            filterWheel1.bindStream(digitalStream1);
            digitalStream1.setBitPosition(filterWheel1, 1);% TODO: confirm bit
            obj.addDevice(filterWheel1);

            filterWheel2 = fieldlab.devices.FilterWheelDevice( ...
                'name', 'Filter Wheel 2', ...
                'comPort', 'COM10', ...              % TODO: confirm COM port
                'ndfValues', [0 0.5 1.0 2.0 3.0 4.0]);% TODO: confirm ND values
            filterWheel2.bindStream(digitalStream1);
            digitalStream1.setBitPosition(filterWheel2, 2);% TODO: confirm bit
            obj.addDevice(filterWheel2);

            filterWheel3 = fieldlab.devices.FilterWheelDevice( ...
                'name', 'Filter Wheel 3', ...
                'comPort', 'COM11', ...              % TODO: confirm COM port
                'ndfValues', [0 0.5 1.0 2.0 3.0 4.0]);% TODO: confirm ND values
            filterWheel3.bindStream(digitalStream1);
            digitalStream1.setBitPosition(filterWheel3, 3);% TODO: confirm bit
            obj.addDevice(filterWheel3);

            %% White LED (+ its color and ND filter wheels) -- currently disabled
            % Output: ao2, Input: ai2
            % whiteLED = symphonyui.builtin.devices.LedDevice(  ...
            %   'LED White',                              ...
            %   daq,                                      ...
            %   'White',                                  ...
            %   'outputStream', 'ao2',                    ...
            %   'inputStream', 'ai2',                     ...
            %   'outputTargetUnits', 'V',                 ...
            %   'inputTargetUnits', 'V',                  ...
            %   'maximum', 10,                            ...
            %   'calibrationLUT', '(None)',               ...
            %   'spectrum', '(None)',                     ...
            %   'ndLUT', '(None)',                        ...
            %   'nd', '',                                 ...
            %   'isLambdaFixed', true,                    ...
            %   'Manufacturer', 'Cairn'                   ...
            %   );
            %
            % Color filter wheel: digital ch 1, COM12
            % whiteLED_cfw = ThorlabsFilterWheel(         ...
            %   'White Color Filter',                     ...
            %   'COM12',                                  ...
            %   'WheelLabels', {'White Color Filters'},   ...
            %   'PositionLabels',                         ...
            %   {                                         ...
            %   {450, 470, 500, 560, 600, 620},           ...
            %   },                                        ...
            %   'verbose', true,                          ...
            %   'Timeout', 0.25                           ...
            %   );
            % whiteLED_cfw.bindPairedDevice(1, whiteLED, 'Color');
            % whiteLED_cfw.bindStream( digitalStream1 );
            % digitalStream1.setBitPosition( whiteLED_cfw, 1 );
            %
            % ND filter wheel: digital ch 2, COM10
            % whiteLED_nd_fw = ThorlabsFilterWheel(       ...
            %   'White ND Filter',                        ...
            %   'COM10',                                  ...
            %   'WheelLabels', {'White ND Filters'},      ...
            %   'PositionLabels',                         ...
            %   {                                         ...
            %   {0.0, 0.5, 1.0, 2.0, 3.0, 4.0},           ...
            %   },                                        ...
            %   'verbose', true,                          ...
            %   'Timeout', 0.25                           ...
            %   );
            % whiteLED_nd_fw.bindPairedDevice(1, whiteLED, 'ND');
            % whiteLED_nd_fw.bindStream( digitalStream1 );
            % digitalStream1.setBitPosition( whiteLED_nd_fw, 2 );
            %
            % obj.addDevice(whiteLED);
            % obj.addDevice(whiteLED_cfw);
            % obj.addDevice(whiteLED_nd_fw);

            %% 405 nm LED (+ its ND filter wheel) -- currently disabled
            % Output: ao3, Input: ai3
            % LED405 = symphonyui.builtin.devices.LedDevice(    ...
            %   'LED 405 nm',                             ...
            %   daq,                                      ...
            %   405,                                      ...
            %   'outputStream', 'ao3',                    ...
            %   'inputStream', 'ai3',                     ...
            %   'outputTargetUnits', 'V',                 ...
            %   'inputTargetUnits', 'V',                  ...
            %   'maximum', 9,                             ...
            %   'calibrationLUT', '(None)',               ...
            %   'spectrum', '(None)',                     ...
            %   'ndLUT', '(None)',                        ...
            %   'nd', '',                                 ...
            %   'isLambdaFixed', true,                    ...
            %   'Manufacturer', 'Cairn'                   ...
            %   );
            %
            % ND filter wheel: digital ch 3, COM11
            % LED405_nd_fw = ThorlabsFilterWheel(         ...
            %   '405 ND Filter',                          ...
            %   'COM11',                                  ...
            %   'WheelLabels', {'LED 405 ND Filter'},     ...
            %   'PositionLabels',                         ...
            %   {                                         ...
            %   {0.0, 0.5, 1.0, 2.0, 3.0, 4.0},           ...
            %   },                                        ...
            %   'verbose', true,                          ...
            %   'Timeout', 0.25                           ...
            %   );
            % LED405_nd_fw.bindPairedDevice(1, LED405, 'ND');
            % LED405_nd_fw.bindStream( digitalStream1 );
            % digitalStream1.setBitPosition( LED405_nd_fw, 3 );
            %
            % obj.addDevice(LED405);
            % obj.addDevice(LED405_nd_fw);

            %% Motorized filter wheel (ThorLabs, common.devices.FilterWheelDevice) -- currently disabled
            % filterWheel = common.devices.FilterWheelDevice( ...
            %   'comPort', 'COM12',                           ...
            %   'ndfValues', [1.0, 2.0, 3.0, 4.0, 5.0, 0]      ...
            %   );
            % Bound to an otherwise-unused stream so its config is written to
            % each epoch.
            % filterWheel.bindStream(digitalStream1);
            % daq.getStream(digitalStream1).setBitPosition(filterWheel, 1);
            % obj.addDevice(filterWheel);

            %% Oscilloscope -- currently disabled
            % Digital bit position: 1 (Tektronix)
            % scope = GenericDevice(  ...
            %   'Oscilloscope',                           ...
            %   symphonyui.core.Measurement.UNITLESS,     ...
            %   daq,                                      ...
            %   'digitalStream', 'doport1',               ...
            %   'type', 'Oscilloscope',                   ...
            %   'bitPosition', 1,                         ...
            %   'manufacturer', 'Tektronix'               ...
            %   );
            % obj.addDevice(scope);
            %
            %% Temperature controller (Warner Instruments TC-324) -- disabled on sim
            % Standard form expected by common.protocols.CommonProtocol, which
            % reads a device named 'Temperature Controller' (in volts) and logs
            % bathTemperature at 100 mV/degree C. Left commented out on the sim
            % rig; enable it in PatchA (the hardware rig).
            %
            % TODO: CONFIRM the analog input channel the Warner controller is
            % wired to. 'ai4' below is a PLACEHOLDER -- the amps already use
            % ai0/ai1, so verify the real channel before recording.
            % temperature = UnitConvertingDevice('Temperature Controller', 'V', 'manufacturer', 'Warner Instruments').bindStream(daq.getStream('ai4'));
            % obj.addDevice(temperature);

        end
    end
end
